config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :currencies
  resources :commodities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commodities#index'
end

app/models/currency.rb
class Currency
  include Mongoid::Document
  field :code, type: String
  field :symbol, type: String
  field :digital_code, type: String
  field :name, type: String
  field :country, type: String
  field :exchange_rate, type: Float
  field :exchange_rate_base, type: String, default: "USD"
  field :exchange_rate_updated_at, type: Time

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:code, :symbol, :digital_code, :name, :country)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :digital_code %>
    <%= form.text_field :digital_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Symbol</th>
      <th>Digital code</th>
      
      <!-- <th>Country</th> -->
      <th>Exchange rate</th>
      <th>Base</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency.name %></td>
        <td><%= currency.code %></td>
        <td><%= currency.symbol %></td>
        <td><%= currency.digital_code %></td>     
        <td><%= currency.exchange_rate %></td>
        <td><%= currency.exchange_rate_base %></td>
        <td><%#= currency.country %></td>
        <td><%= link_to 'Show', currency %></td>
        <td><%#= link_to 'Edit', edit_currency_path(currency) %></td>
        <td><%#= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @currency.code %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @currency.symbol %>
</p>

<p>
  <strong>Digital code:</strong>
  <%= @currency.digital_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @currency.country %>
</p>

<p>
  <strong>Exchange rate:</strong>
  <%= @currency.exchange_rate %>
</p>

<p>
  <strong>Exchange rate base:</strong>
  <%= @currency.exchange_rate_base %>
</p>

<p>
  <strong>Exchange rate updated at:</strong>
  <%= @currency.exchange_rate_updated_at %>
</p>


<%#= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>