config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :currencies
  resources :commodities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commodities#index'
end

app/models/commodity.rb
class Commodity
  include Mongoid::Document
  field :name, type: String
  field :price, type: Float
  field :date, type: Date

  paginates_per 50
  belongs_to :category
  default_scope   { order_by(date: :desc) }

  %w(gold silver).each do |commodity|
  	scope commodity, -> { where(name: "#{commodity.capitalize}") }
  end
  #scope :gold, -> { where(name: "Gold") }
 
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  before_action :set_commodity, only: [:show, :edit, :update, :destroy]

  # GET /commodities
  # GET /commodities.json
  def index
    @commodities = Commodity.page params[:page]
  end

  # GET /commodities/1
  # GET /commodities/1.json
  def show
  end

  # GET /commodities/new
  def new
    @commodity = Commodity.new
  end

  # GET /commodities/1/edit
  def edit
  end

  # POST /commodities
  # POST /commodities.json
  def create
    @commodity = Commodity.new(commodity_params)

    respond_to do |format|
      if @commodity.save
        format.html { redirect_to @commodity, notice: 'Commodity was successfully created.' }
        format.json { render :show, status: :created, location: @commodity }
      else
        format.html { render :new }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commodities/1
  # PATCH/PUT /commodities/1.json
  def update
    respond_to do |format|
      if @commodity.update(commodity_params)
        format.html { redirect_to @commodity, notice: 'Commodity was successfully updated.' }
        format.json { render :show, status: :ok, location: @commodity }
      else
        format.html { render :edit }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commodities/1
  # DELETE /commodities/1.json
  def destroy
    @commodity.destroy
    respond_to do |format|
      format.html { redirect_to commodities_url, notice: 'Commodity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commodity
      @commodity = Commodity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commodity_params
      params.require(:commodity).permit(:name, :category_id)
    end
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/views/commodities/_form.html.erb
<%= form_with(model: commodity, local: true) do |form| %>
  <% if commodity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commodity.errors.count, "error") %> prohibited this commodity from being saved:</h2>

      <ul>
      <% commodity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/commodities/edit.html.erb
<h1>Editing Commodity</h1>

<%= render 'form', commodity: @commodity %>

<%= link_to 'Show', @commodity %> |
<%= link_to 'Back', commodities_path %>

app/views/commodities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commodities</h1>

<table>
  <thead>
    <tr>
      <th>Sl.No</th>
      <th>Name</th>
      <th>Date</th>
      <th>Price</th>
      <!-- <th></th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commodities.each_with_index do |commodity, index| %>
      <tr>
        <td><%= index + 1 %> </td>
        <td><%= commodity.name %></td>
        <td><%= commodity.date %></td>
        <td><%= number_to_currency_rs(commodity.price) %></td>
        <!-- <td><%= commodity.category %></td> -->
        <td><%= link_to 'Show', commodity %></td>
        <td><%#= link_to 'Edit', edit_commodity_path(commodity) %></td>
        <td><%#= link_to 'Destroy', commodity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Commodity', new_commodity_path %>

<%= paginate @commodities %>

app/views/commodities/new.html.erb
<h1>New Commodity</h1>

<%= render 'form', commodity: @commodity %>

<%= link_to 'Back', commodities_path %>

app/views/commodities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @commodity.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @commodity.category.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency_rs(@commodity.price) %>
</p>


<%#= link_to 'Edit', edit_commodity_path(@commodity) %> |
<%= link_to 'Back', commodities_path %>